import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mafe:</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>

            <main className={styles.main}>
                <h1 className={styles.title}>Mafe:</h1>
                <p className={styles.content}>
                En medio de la ansiedad y decepción que estás sintiendo, creo que es oportuno que te escriba una palabra que para nosotros va a ser vital si queremos que esto funcione:
                <br/>
                Perdón.
                <br/>
                Por ser tan egoísta, tan indiferente, tan amargo. No quiero hablar más de mí, nuestra relación no debe ser así. He estado tan ocupado y ansioso en estas semanas que no me he dado el tiempo de darte la palabra, de escucharte.
                <br/>
                Es difícil para nosotros los hombres escuchar detenidamente y con ese cariño con el que escuchan las mujeres., pero, así como es difícil, es un deber que tengo para que esta relación funcione. Así como tú escuchas, aconsejas, esperas, y amas, mereces a alguien que por lo menos esté dispuesto a escucharte en el momento un audio de un minuto y un poco más. Y no lo he sido. 
                <br/>
                Creo que los dos queremos que esto funcione, porque sentimos que esto es de Dios y muchas veces nos acerca, nos alegra, pero necesito que me des una chance de mejorar ese defecto que tengo. Quiero llegar ahorita con un ramo de flores y una caja de chocolates a tu casa en agradecimiento a todo lo que hemos pasado esta semana, pero me dijiste que no son necesarios esos detalles. Creo que otro tipo de detalle te hará mejor: que te escuche con la misma atención con la que nos escucha Dios. Porque lo mereces Mafe, lo mereces.
                <br/>
                No te puedo prometer siempre estar ahí, porque soy un hombre limitado, pero te puedo prometer dar lo mejor para cambiar, poniendo eso en la oración. Si lo ponemos en Dios, Él nos escuchará, tenlo por seguro.
                </p>
                <p className={styles.signature}>Perdón por ser un tonto, gracias por tanto, <br/>Nico</p>
            </main>
        </div>
    </>
  );
}
