import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Me debes un abrazo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>

            <main className={styles.main}>
                <h1 className={styles.title}>Mafe:</h1>
                <p className={styles.content}>
                La verdad, me quedan cortas las palabras en la oración para agradecerle a Dios por esto que estamos teniendo. Ya te lo he dicho, estoy bien enamorado de ti. No solo porque eres guapa y me atraes físicamente, sino que me encanta tu forma de ser, tu forma de pensar, tu forma de vivir la fe, tu forma de apoyar mis planes, tu forma de buscar siempre mi bienestar. Me quedo corto si quiero agradecerle a Dios por toda la verdad.
                    <br /><br />
                    Y creo que ya te lo he dicho, pero me enamoré de ti cuando empecé a escucharte en Brasil. Hoy en día un joven católico tendría que ir hasta fondo del mar para encontrar una mujer tan piadosa, respetuosa y pura como tú. Me motivas a ser mejor. Siento que antes mi vida era muy buena, tenia casi todo lo que necesita un cristiano: los sacramentos, la oración y todo lo que ya sabemos que nos acerca a Dios, pero me faltaba algo, un camino, una vocación cristiana, un trazo claro como camino para ir al Cielo. Creo que ese camino, esa vocación cristiana, la estoy encontrando en esta relación contigo que nos está llevando cerca de Dios. Ir a Misa ahora para mi es diferente, no solo me preocupo por ser santo yo, sino que ahora también me preocupo por ti y es hermoso, porque me está haciendo crecer en generosidad y caridad. Me estás haciendo mejor Mafe.
                    <br /><br />
                    Cuentas conmigo para rezar, hablar, que me cuentes tus problemas, para todo. Llegando al Cielo le agradeceré a Dios por haberte conocido. 
<br/>Quiero y elegiría una y mil veces ir contigo por ese camino estrecho que lleva al Cielo. Estoy super motivado por lo que viene.

                </p>
                <p className={styles.signature}>Love u,<br />Nico</p>
            </main>
        </div>
    </>
  );
}
